#!/bin/bash
set -euo pipefail

AGENT_NAME="rust-embedded-agent"
TOOLCHAIN="${1:-stable}"
AGENT_NUMBER="${2:-1}"

if [ -z "${BUILDKITE_AGENT_TOKEN:-}" ]
then
  export BUILDKITE_AGENT_TOKEN="$(security find-generic-password -l "Buildkite Agent Token: $AGENT_NAME" -w)"
fi
if [ -z "${BUILDKITE_AGENT_TOKEN}" ]
then
  echo "Could not find Buildkite credentials" 1>&2
  exit 1
fi

tag="$AGENT_NAME:$TOOLCHAIN"
docker build --build-arg TOOLCHAIN="$TOOLCHAIN" --tag "$tag" agent

# Extract buildkite agent labels from the image
metadata="$(docker inspect -f '{{ index .Config.Labels "buildkite.metadata" }}' "${tag}")"

cache="${AGENT_NAME}-cache"
docker volume create --name "${cache}"

docker run \
  --init \
  --detach \
  --restart always \
  --name "${AGENT_NAME}-${AGENT_NUMBER}" \
  --hostname "${AGENT_NAME}-${AGENT_NUMBER}" \
  --volume ~/.ssh/buildkite:/root/.ssh/id_rsa \
  --volume "${cache}":/root/.cargo \
  --env BUILDKITE_GIT_CLEAN_FLAGS="-fdq" \
  --env BUILDKITE_AGENT_TOKEN \
  --env BUILDKITE_AGENT_META_DATA="${metadata}" \
  --env BUILDKITE_AGENT_SPAWN=4 \
  "$tag"
